
//auth.js
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ID = 'SET_ID'
export const SET_NAME = 'SET_NAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_SCHOOL = 'SET_SCHOOL'
export const SET_ROLE = 'SET_ROLE'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const SET_EMAIL_VERIFIED_STATUS = 'SET_EMAIL_VERIFIED_STATUS'
export const LOGOUT = 'LOGOUT'

//search.js
export const SET_SEARCH_USSTATE = 'SET_SEARCH_USSTATE'
export const SET_SEARCH_ADDRESS = 'SET_SEARCH_ADDRESS'
export const SET_SEARCH_COORDINATE = 'SET_SEARCH_COORDINATE'
export const SET_SEARCH_CATEGORIES = 'SET_SEARCH_CATEGORIES'
export const SET_SEARCH_COMPANY_NAME = 'SET_SEARCH_COMPANY_NAME'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_PAGINATION = 'SET_SEARCH_PAGINATION'

//list.js
export const SET_LIST_LISTINFO = 'SET_LIST_LISTINFO'
export const SET_LIST_CALENDAR = 'SET_LIST_CALENDAR'
export const SET_LIST_PREVIOUS_APPOINTMENT = 'SET_LIST_PREVIOUS_APPOINTMENT'
export const SHOW_LIST_APPOINTMENT_TOOL = 'SHOW_APPOINTMENT_TOOL'
export const HIDE_LIST_APPOINTMENT_TOOL = 'HIDE_APPOINTMENT_TOOL'
export const SET_LIST_TAB = 'SET_LIST_TAB'
export const SET_LIST_CALENDAR_CONTROL = 'SET_LIST_CALENDAR_CONTROL'
export const SET_LIST_CALENDAR_SCHEDULE = 'SET_LIST_CALENDAR_SCHEDULE'

//dashboard.js
export const SET_DASHBOARD_USERINFO = 'SET_DASHBOARD_USERINFO'
export const SET_DASHBOARD_LISTINFO = 'SET_DASHBOARD_LISTINFO'
export const SET_DASHBOARD_APPOINTMENT = 'SET_DASHBOARD_APPOINTMENT'
export const START_EDIT_LISTINFO = 'START_EDIT_LISTINFO'
export const END_EDIT_LISTINFO = 'END_EDIT_LISTINFO'
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'

//clientbook.js
export const SET_CLIENTBOOK_SHARELIST_CLIENTS = 'SET_CLIENTBOOK_SHARELIST_CLIENTS'
export const SET_CLIENTBOOK_SHARELIST_SELECTED_CLIENT = 'SET_CLIENTBOOK_SHARELIST_SELECTED_CLIENT'
export const SET_CLIENTBOOK_SHARELIST_ADDCLIENTBUTTON_STATUS = 'SET_CLIENTBOOK_SHARELIST_ADDCLIENTBUTTON_STATUS'

export const SET_CLIENTBOOK_CLIENTS = 'SET_CLIENTBOOK_CLIENTS'
export const SET_CLIENTBOOK_SELECTED_CLIENT = 'SET_CLIENTBOOK_SELECTED_CLIENT'
export const SET_CLIENTBOOK_ADDCLIENTBUTTON_STATUS = 'SET_CLIENTBOOK_ADDCLIENTBUTTON_STATUS'
export const SET_CLIENTBOOK_ADDAPPOINTMENTMODAL_STATUS = 'SET_CLIENTBOOK_ADDAPPOINTMENTMODAL_STATUS'
export const SET_CLIENTBOOK_NEWAPPOINTMENT = 'SET_CLIENTBOOK_NEWAPPOINTMENT'
export const GET_CLIENTBOOK_APPOINTMENT_SUCCESS = 'GET_CLIENTBOOK_APPOINTMENT_SUCCESS'

export const FETCH_SHARELIST_CLIENTS_SUCCESS = 'FETCH_SHARELIST_CLIENTS_SUCCESS'
export const FETCH_SHARELIST_CLIENTS_FAILURE = 'FETCH_SHARELIST_CLIENTS_FAILURE'
export const CREATE_SHARELIST_CLIENT_SUCCESS = 'CREATE_SHARELIST_CLIENT_SUCCESS'
export const CREATE_SHARELIST_CLIENT_FAILURE = 'CREATE_SHARELIST_CLIENT_FAILURE'
export const UPDATE_SHARELIST_CLIENT_SUCCESS = 'UPDATE_SHARELIST_CLIENT_SUCCESS'
export const UPDATE_SHARELIST_CLIENT_FAILURE = 'UPDATE_SHARELIST_CLIENT_FAILURE'
export const DELETE_SHARELIST_CLIENT_SUCCESS = 'DELETE_SHARELIST_CLIENT_SUCCESS'
export const DELETE_SHARELIST_CLIENT_FAILURE = 'DELETE_SHARELIST_CLIENT_FAILURE'

export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENT_SUCCESS'
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENT_FAILURE'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE'
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS'
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE'
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS'
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE'

//view.js
export const SET_VIEW_SNACKBAR_STATUS = 'SET_VIEW_SNACKBAR_STATUS'
export const SET_VIEW_DRAWER_STATUS = 'SET_VIEW_DRAWER_STATUS'
export const SET_VIEW_MESSAGEBOX_STATUS = 'SET_VIEW_MESSAGEBOX_STATUS'
export const SET_VIEW_PROGRESSMODAL_STATUS = 'SET_VIEW_PROGRESSMODAL_STATUS'

//internal.js
export const INTERNAL_SET_PUBLIC_ADVISORS = 'INTERNAL_SET_PUBLIC_ADVISORS'
export const INTERNAL_SET_NEWPUBLICADVISORFORM_STATUS = 'INTERNAL_SET_NEWPUBLICADVISORFORM_STATUS'

//function.js
export const ENABLE_AGENTBOOK = 'ENABLE_AGENTBOOK'
export const ENABLE_SHARELIST = 'ENABLE_SHARELIST'

//data.js
export const FETCH_ARTICLES = 'FETCH_ARTICLES'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL'
export const CREATE_NEW_ARTICLE = 'CREATE_NEW_ARTICLE'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const CREATE_NEW_CARDTEMPLATE = 'CREATE_NEW_CARDTEMPLATE'
export const UPDATE_CARDTEMPLATE = 'UPDATE_CARDTEMPLATE'
export const FETCH_CARDTEMPLATES = 'FETCH_CARDTEMPLATES'
export const FETCH_CARDTEMPLATE = 'FETCH_CARDTEMPLATE'
export const FETCH_CARDTEMPLATES_SUCCESS = 'FETCH_CARDTEMPLATES_SUCCESS'
export const FETCH_CARDTEMPLATE_SUCCESS = 'FETCH_CARDTEMPLATE_SUCCESS'
